name: Api Slurp

on: [push]

jobs:
  api-slurp-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Call CONTENTdm api
        run: |
          curl -X GET -H 'Content-Type: text/plain' 'https://content.libraries.wsu.edu/digital/bl/dmwebservices/index.php?q=dmQuery/senex/0/0/nosort/1024/10/0/0/0/json' >> result.json
      - name: Upload api data as artifact
        uses: actions/upload-artifact@v3
        with:
          name: result
          path: ./.github/workflows/result.json
