on: [push]

jobs:
  api-get:
    runs-on: ubuntu-latest
    name: Checkout repo and grab api data.
    steps:
      - uses: actions/checkout@v3
      - id: checkout
        uses: ./action.yml
      - run: echo "Done."
        shell: bash
