on: [push]

jobs:
  api-get:
    runs-on: ubuntu-latest
    name: Grab api data.
    steps:
      - name: API Grabber
        uses: ThatTimothy/api-grabber@v1.0.0
        with:
          options: "../../options.json"
